import type { Listing, CropType, ListingType, User } from "./types"

// Mock listings data for demo
export const mockListings: Listing[] = [
  // Coffee Plantations
  {
    id: "1",
    title: "50 Acres Coffee Plantation - Kiambu",
    description:
      "Well-established coffee plantation with mature trees. Excellent soil quality and reliable water source. Perfect for experienced coffee farmers.",
    type: "plantation",
    cropType: "coffee",
    county: "Kiambu",
    size: "50 acres",
    price: 150000,
    priceUnit: "per year",
    photos: ["/coffee-plantation-kenya.jpg"],
    whatsappNumber: "+254712345678",
    ownerId: "3",
    owner: {
      id: "3",
      name: "Mary Landowner",
      phone: "+254712345678",
      email: "mary@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 12,
    },
    latitude: -1.1611,
    longitude: 36.8193,
    videos: [
      {
        id: "v1",
        title: "Coffee Plantation Overview",
        thumbnail: "/placeholder.svg?key=coffee1",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
      {
        id: "v2",
        title: "Harvesting Process",
        thumbnail: "/placeholder.svg?key=coffee2",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
    ],
    status: "approved",
    featured: true,
    views: 245,
    favorites: 18,
    averageRating: 4.6,
    reviewCount: 8,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "5",
    title: "Premium Coffee Estate - Nyeri",
    description: "High-altitude coffee plantation producing AA grade beans. Established processing facility included.",
    type: "plantation",
    cropType: "coffee",
    county: "Nyeri",
    size: "75 acres",
    price: 220000,
    priceUnit: "per year",
    photos: ["/coffee-plantation-kenya.jpg"],
    whatsappNumber: "+254756789012",
    ownerId: "4",
    owner: {
      id: "4",
      name: "David Coffee Estate",
      phone: "+254756789012",
      email: "david@example.com",
      verified: true,
      rating: 4.9,
      reviewCount: 15,
    },
    latitude: -0.4399,
    longitude: 36.9115,
    videos: [
      {
        id: "v3",
        title: "Estate Walkthrough",
        thumbnail: "/placeholder.svg?key=coffee3",
        url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
    ],
    status: "approved",
    featured: true,
    views: 189,
    favorites: 14,
    averageRating: 4.7,
    reviewCount: 10,
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "6",
    title: "Organic Coffee Farm - Murang'a",
    description:
      "Certified organic coffee plantation with sustainable farming practices. Great for eco-conscious farmers.",
    type: "plantation",
    cropType: "coffee",
    county: "Murang'a",
    size: "30 acres",
    price: 120000,
    priceUnit: "per year",
    photos: ["/coffee-plantation-kenya.jpg"],
    whatsappNumber: "+254767890123",
    ownerId: "5",
    owner: {
      id: "5",
      name: "Grace Wanjiku",
      phone: "+254767890123",
      email: "grace@example.com",
      verified: true,
      rating: 4.5,
      reviewCount: 9,
    },
    status: "approved",
    featured: false,
    views: 189,
    favorites: 14,
    averageRating: 4.4,
    reviewCount: 6,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },

  // Tea Plantations
  {
    id: "4",
    title: "Tea Plantation - Kericho",
    description:
      "Established tea plantation in the heart of Kericho. High altitude location with perfect climate for tea production.",
    type: "plantation",
    cropType: "tea",
    county: "Kericho",
    size: "25 acres",
    price: 200000,
    priceUnit: "per year",
    photos: ["/tea-plantation-kericho-kenya.jpg"],
    whatsappNumber: "+254745678901",
    ownerId: "3",
    owner: {
      id: "3",
      name: "Mary Landowner",
      phone: "+254745678901",
      email: "mary@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 12,
    },
    status: "approved",
    featured: true,
    views: 278,
    favorites: 22,
    averageRating: 4.8,
    reviewCount: 13,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "7",
    title: "Highland Tea Estate - Nandi",
    description: "Premium tea plantation at 2000m altitude. Excellent yields and quality tea production.",
    type: "plantation",
    cropType: "tea",
    county: "Nandi",
    size: "40 acres",
    price: 180000,
    priceUnit: "per year",
    photos: ["/tea-plantation-kericho-kenya.jpg"],
    whatsappNumber: "+254778901234",
    ownerId: "6",
    owner: {
      id: "6",
      name: "Samuel Kipchoge",
      phone: "+254778901234",
      email: "samuel@example.com",
      verified: false,
      rating: 4.3,
      reviewCount: 7,
    },
    status: "approved",
    featured: false,
    views: 156,
    favorites: 11,
    averageRating: 4.2,
    reviewCount: 5,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "8",
    title: "Bomet Tea Gardens",
    description: "Well-maintained tea plantation with modern irrigation system. Ready for immediate cultivation.",
    type: "plantation",
    cropType: "tea",
    county: "Bomet",
    size: "60 acres",
    price: 250000,
    priceUnit: "per year",
    photos: ["/tea-plantation-kericho-kenya.jpg"],
    whatsappNumber: "+254789012345",
    ownerId: "7",
    owner: {
      id: "7",
      name: "Rose Chebet",
      phone: "+254789012345",
      email: "rose@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 10,
    },
    status: "approved",
    featured: true,
    views: 334,
    favorites: 28,
    averageRating: 4.6,
    reviewCount: 9,
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
  },

  // Maize Farms
  {
    id: "2",
    title: "Prime Agricultural Land - Nakuru",
    description:
      "Fertile land suitable for maize and wheat farming. Located near main road with easy access to markets.",
    type: "land",
    cropType: "maize",
    county: "Nakuru",
    size: "100 acres",
    price: 80000,
    priceUnit: "per season",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254723456789",
    ownerId: "3",
    owner: {
      id: "3",
      name: "Mary Landowner",
      phone: "+254723456789",
      email: "mary@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 12,
    },
    status: "approved",
    featured: false,
    views: 198,
    favorites: 16,
    averageRating: 4.5,
    reviewCount: 7,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "9",
    title: "Maize Farm - Trans Nzoia",
    description: "Large scale maize farming land in Kenya's breadbasket. Excellent soil fertility and rainfall.",
    type: "land",
    cropType: "maize",
    county: "Trans Nzoia",
    size: "200 acres",
    price: 120000,
    priceUnit: "per season",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254790123456",
    ownerId: "8",
    owner: {
      id: "8",
      name: "Peter Wekesa",
      phone: "+254790123456",
      email: "peter@example.com",
      verified: true,
      rating: 4.6,
      reviewCount: 14,
    },
    status: "approved",
    featured: true,
    views: 267,
    favorites: 21,
    averageRating: 4.4,
    reviewCount: 8,
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-11"),
  },
  {
    id: "10",
    title: "Uasin Gishu Maize Fields",
    description: "Mechanized farming ready land with storage facilities. Perfect for commercial maize production.",
    type: "land",
    cropType: "maize",
    county: "Uasin Gishu",
    size: "150 acres",
    price: 100000,
    priceUnit: "per season",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254701234567",
    ownerId: "9",
    owner: {
      id: "9",
      name: "David Koech",
      phone: "+254701234567",
      email: "david@example.com",
      verified: true,
      rating: 4.5,
      reviewCount: 13,
    },
    status: "approved",
    featured: false,
    views: 234,
    favorites: 19,
    averageRating: 4.3,
    reviewCount: 7,
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-13"),
  },
  {
    id: "11",
    title: "Bungoma Maize Plantation",
    description: "Rich volcanic soil perfect for maize cultivation. Includes farm workers' quarters.",
    type: "land",
    cropType: "maize",
    county: "Bungoma",
    size: "80 acres",
    price: 60000,
    priceUnit: "per season",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254712345670",
    ownerId: "10",
    owner: {
      id: "10",
      name: "Alice Wafula",
      phone: "+254712345670",
      email: "alice@example.com",
      verified: true,
      rating: 4.4,
      reviewCount: 11,
    },
    status: "approved",
    featured: false,
    views: 210,
    favorites: 17,
    averageRating: 4.2,
    reviewCount: 6,
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17"),
  },

  // Sugarcane Plantations
  {
    id: "12",
    title: "Sugarcane Estate - Kakamega",
    description: "Established sugarcane plantation near Mumias Sugar Factory. Guaranteed market for produce.",
    type: "plantation",
    cropType: "sugarcane",
    county: "Kakamega",
    size: "120 acres",
    price: 180000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254723456781",
    ownerId: "11",
    owner: {
      id: "11",
      name: "Francis Shiundu",
      phone: "+254723456781",
      email: "francis@example.com",
      verified: true,
      rating: 4.6,
      reviewCount: 14,
    },
    status: "approved",
    featured: true,
    views: 289,
    favorites: 24,
    averageRating: 4.5,
    reviewCount: 9,
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09"),
  },
  {
    id: "13",
    title: "Busia Sugarcane Farm",
    description: "Prime sugarcane growing land with irrigation infrastructure. Close to processing facilities.",
    type: "plantation",
    cropType: "sugarcane",
    county: "Busia",
    size: "90 acres",
    price: 140000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254734567892",
    ownerId: "12",
    owner: {
      id: "12",
      name: "Margaret Ochieng",
      phone: "+254734567892",
      email: "margaret@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 15,
    },
    status: "approved",
    featured: false,
    views: 260,
    favorites: 21,
    averageRating: 4.6,
    reviewCount: 10,
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21"),
  },
  {
    id: "14",
    title: "Kisumu Sugarcane Plantation",
    description: "Lakeside sugarcane farm with excellent water access. Established cane varieties.",
    type: "plantation",
    cropType: "sugarcane",
    county: "Kisumu",
    size: "70 acres",
    price: 110000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254745678903",
    ownerId: "13",
    owner: {
      id: "13",
      name: "James Otieno",
      phone: "+254745678903",
      email: "james@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 16,
    },
    status: "approved",
    featured: false,
    views: 240,
    favorites: 19,
    averageRating: 4.7,
    reviewCount: 11,
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19"),
  },

  // Cotton Farms
  {
    id: "15",
    title: "Cotton Farm - Machakos",
    description: "Dry land cotton farming with drought-resistant varieties. Suitable for semi-arid conditions.",
    type: "land",
    cropType: "cotton",
    county: "Machakos",
    size: "60 acres",
    price: 45000,
    priceUnit: "per season",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254756789014",
    ownerId: "14",
    owner: {
      id: "14",
      name: "Joseph Mutua",
      phone: "+254756789014",
      email: "joseph@example.com",
      verified: true,
      rating: 4.6,
      reviewCount: 13,
    },
    status: "approved",
    featured: false,
    views: 220,
    favorites: 17,
    averageRating: 4.5,
    reviewCount: 8,
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: "16",
    title: "Makueni Cotton Estate",
    description: "Large cotton plantation with modern farming techniques. Includes ginning facility access.",
    type: "land",
    cropType: "cotton",
    county: "Makueni",
    size: "100 acres",
    price: 70000,
    priceUnit: "per season",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254767890125",
    ownerId: "15",
    owner: {
      id: "15",
      name: "Ruth Mwende",
      phone: "+254767890125",
      email: "ruth@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 14,
    },
    status: "approved",
    featured: false,
    views: 250,
    favorites: 20,
    averageRating: 4.6,
    reviewCount: 9,
    createdAt: new Date("2024-01-23"),
    updatedAt: new Date("2024-01-23"),
  },
  {
    id: "17",
    title: "Kitui Cotton Fields",
    description: "Established cotton farm with water harvesting systems. Perfect for commercial cotton production.",
    type: "land",
    cropType: "cotton",
    county: "Kitui",
    size: "85 acres",
    price: 55000,
    priceUnit: "per season",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254778901236",
    ownerId: "16",
    owner: {
      id: "16",
      name: "Paul Kioko",
      phone: "+254778901236",
      email: "paul@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: false,
    views: 230,
    favorites: 18,
    averageRating: 4.7,
    reviewCount: 10,
    createdAt: new Date("2024-01-24"),
    updatedAt: new Date("2024-01-24"),
  },

  // Farm Machinery
  {
    id: "3",
    title: "John Deere Tractor for Lease",
    description: "Well-maintained John Deere tractor available for seasonal lease. Includes operator if needed.",
    type: "machinery",
    county: "Meru",
    size: "75HP",
    price: 25000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254734567890",
    ownerId: "3",
    owner: {
      id: "3",
      name: "Mary Landowner",
      phone: "+254734567890",
      email: "mary@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 12,
    },
    status: "pending",
    featured: false,
    views: 89,
    favorites: 7,
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "18",
    title: "Massey Ferguson Tractor - Narok",
    description: "Heavy-duty tractor perfect for large scale farming. Available with various implements.",
    type: "machinery",
    county: "Narok",
    size: "85HP",
    price: 30000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254789012347",
    ownerId: "17",
    owner: {
      id: "17",
      name: "Simon Sankale",
      phone: "+254789012347",
      email: "simon@example.com",
      verified: false,
      rating: 4.2,
      reviewCount: 5,
    },
    status: "approved",
    featured: true,
    views: 145,
    favorites: 12,
    averageRating: 4.1,
    reviewCount: 4,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "19",
    title: "Combine Harvester - Laikipia",
    description: "Modern combine harvester for wheat and maize. Includes transportation and operator.",
    type: "machinery",
    county: "Laikipia",
    size: "Class 6",
    price: 80000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254790123458",
    ownerId: "18",
    owner: {
      id: "18",
      name: "Robert Kariuki",
      phone: "+254790123458",
      email: "robert@example.com",
      verified: true,
      rating: 4.9,
      reviewCount: 16,
    },
    status: "approved",
    featured: true,
    views: 130,
    favorites: 11,
    averageRating: 4.8,
    reviewCount: 10,
    createdAt: new Date("2024-01-07"),
    updatedAt: new Date("2024-01-07"),
  },
  {
    id: "20",
    title: "Irrigation Equipment - Embu",
    description: "Complete drip irrigation system for hire. Perfect for vegetable and fruit farming.",
    type: "machinery",
    county: "Embu",
    size: "50 acres capacity",
    price: 15000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254701234569",
    ownerId: "19",
    owner: {
      id: "19",
      name: "Catherine Njeri",
      phone: "+254701234569",
      email: "catherine@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 14,
    },
    status: "approved",
    featured: false,
    views: 95,
    favorites: 8,
    averageRating: 4.6,
    reviewCount: 9,
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-26"),
  },
  {
    id: "21",
    title: "Disc Plough Set - Nyandarua",
    description: "Heavy-duty disc ploughs for land preparation. Suitable for various soil types.",
    type: "machinery",
    county: "Nyandarua",
    size: "24 disc",
    price: 12000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254712345671",
    ownerId: "20",
    owner: {
      id: "20",
      name: "Michael Kamau",
      phone: "+254712345671",
      email: "michael@example.com",
      verified: true,
      rating: 4.5,
      reviewCount: 12,
    },
    status: "approved",
    featured: false,
    views: 110,
    favorites: 9,
    averageRating: 4.4,
    reviewCount: 7,
    createdAt: new Date("2024-01-27"),
    updatedAt: new Date("2024-01-27"),
  },
  {
    id: "31",
    title: "New Holland Tractor - Nakuru",
    description: "Powerful 90HP New Holland tractor with front loader. Perfect for heavy farming operations.",
    type: "machinery",
    county: "Nakuru",
    size: "90HP",
    price: 35000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254712345672",
    ownerId: "30",
    owner: {
      id: "30",
      name: "Peter Kimani",
      phone: "+254712345672",
      email: "peter@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: true,
    views: 160,
    favorites: 14,
    averageRating: 4.7,
    reviewCount: 11,
    createdAt: new Date("2024-02-04"),
    updatedAt: new Date("2024-02-04"),
  },
  {
    id: "32",
    title: "Seed Drill Machine - Trans Nzoia",
    description: "Precision seed drill for maize and wheat planting. Ensures optimal seed spacing and depth.",
    type: "machinery",
    county: "Trans Nzoia",
    size: "12 row",
    price: 18000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254723456783",
    ownerId: "31",
    owner: {
      id: "31",
      name: "Sarah Wekesa",
      phone: "+254723456783",
      email: "sarah@example.com",
      verified: true,
      rating: 4.6,
      reviewCount: 13,
    },
    status: "approved",
    featured: false,
    views: 140,
    favorites: 12,
    averageRating: 4.5,
    reviewCount: 8,
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "33",
    title: "Rotary Harrow - Uasin Gishu",
    description: "Heavy-duty rotary harrow for seedbed preparation. Excellent for breaking clods and leveling.",
    type: "machinery",
    county: "Uasin Gishu",
    size: "3.5m width",
    price: 14000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254734567894",
    ownerId: "32",
    owner: {
      id: "32",
      name: "Joseph Koech",
      phone: "+254734567894",
      email: "joseph@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 14,
    },
    status: "approved",
    featured: false,
    views: 120,
    favorites: 10,
    averageRating: 4.6,
    reviewCount: 7,
    createdAt: new Date("2024-02-06"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    id: "34",
    title: "Boom Sprayer - Kiambu",
    description: "Self-propelled boom sprayer for crop protection. Covers large areas efficiently.",
    type: "machinery",
    county: "Kiambu",
    size: "24m boom",
    price: 22000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254745678905",
    ownerId: "33",
    owner: {
      id: "33",
      name: "Grace Mwangi",
      phone: "+254745678905",
      email: "grace@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: false,
    views: 135,
    favorites: 11,
    averageRating: 4.7,
    reviewCount: 8,
    createdAt: new Date("2024-02-07"),
    updatedAt: new Date("2024-02-07"),
  },
  {
    id: "35",
    title: "Maize Sheller Machine - Bungoma",
    description: "Electric maize shelling machine for post-harvest processing. High capacity and efficiency.",
    type: "machinery",
    county: "Bungoma",
    size: "2 ton/hour",
    price: 8000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254756789016",
    ownerId: "34",
    owner: {
      id: "34",
      name: "David Wafula",
      phone: "+254756789016",
      email: "david@example.com",
      verified: true,
      rating: 4.6,
      reviewCount: 13,
    },
    status: "approved",
    featured: false,
    views: 125,
    favorites: 10,
    averageRating: 4.5,
    reviewCount: 7,
    createdAt: new Date("2024-02-08"),
    updatedAt: new Date("2024-02-08"),
  },
  {
    id: "36",
    title: "Subsoiler - Machakos",
    description: "Deep tillage subsoiler for breaking hardpan. Improves water infiltration and root penetration.",
    type: "machinery",
    county: "Machakos",
    size: "5 tine",
    price: 10000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254767890127",
    ownerId: "35",
    owner: {
      id: "35",
      name: "Mary Mutua",
      phone: "+254767890127",
      email: "mary@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 14,
    },
    status: "approved",
    featured: false,
    views: 115,
    favorites: 9,
    averageRating: 4.6,
    reviewCount: 6,
    createdAt: new Date("2024-02-09"),
    updatedAt: new Date("2024-02-09"),
  },
  {
    id: "37",
    title: "Fertilizer Spreader - Meru",
    description: "Broadcast fertilizer spreader with adjustable rate control. Ensures uniform application.",
    type: "machinery",
    county: "Meru",
    size: "1000kg capacity",
    price: 6000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254778901238",
    ownerId: "36",
    owner: {
      id: "36",
      name: "John Mwenda",
      phone: "+254778901238",
      email: "john@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: false,
    views: 105,
    favorites: 8,
    averageRating: 4.7,
    reviewCount: 7,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "38",
    title: "Mower Conditioner - Nandi",
    description: "Hay mower and conditioner for pasture management. Perfect for dairy farms.",
    type: "machinery",
    county: "Nandi",
    size: "2.4m cut width",
    price: 16000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254789012349",
    ownerId: "37",
    owner: {
      id: "37",
      name: "Rebecca Kipchoge",
      phone: "+254789012349",
      email: "rebecca@example.com",
      verified: true,
      rating: 4.9,
      reviewCount: 16,
    },
    status: "approved",
    featured: false,
    views: 150,
    favorites: 12,
    averageRating: 4.8,
    reviewCount: 10,
    createdAt: new Date("2024-02-11"),
    updatedAt: new Date("2024-02-11"),
  },
  {
    id: "39",
    title: "Potato Planter - Nyandarua",
    description: "Automatic potato planting machine with fertilizer attachment. Increases planting efficiency.",
    type: "machinery",
    county: "Nyandarua",
    size: "4 row",
    price: 20000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254790123460",
    ownerId: "38",
    owner: {
      id: "38",
      name: "Francis Kamau",
      phone: "+254790123460",
      email: "francis@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 14,
    },
    status: "approved",
    featured: false,
    views: 140,
    favorites: 11,
    averageRating: 4.6,
    reviewCount: 7,
    createdAt: new Date("2024-02-12"),
    updatedAt: new Date("2024-02-12"),
  },
  {
    id: "40",
    title: "Threshing Machine - Kirinyaga",
    description: "Multi-crop threshing machine for rice, wheat, and barley. Clean grain separation.",
    type: "machinery",
    county: "Kirinyaga",
    size: "5HP engine",
    price: 12000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254701234571",
    ownerId: "39",
    owner: {
      id: "39",
      name: "Agnes Wanjiru",
      phone: "+254701234571",
      email: "agnes@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: false,
    views: 125,
    favorites: 10,
    averageRating: 4.7,
    reviewCount: 8,
    createdAt: new Date("2024-02-13"),
    updatedAt: new Date("2024-02-13"),
  },
  {
    id: "41",
    title: "Water Pump Set - Kajiado",
    description: "High-capacity water pump for irrigation. Diesel engine with long service life.",
    type: "machinery",
    county: "Kajiado",
    size: "6 inch outlet",
    price: 9000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254712345673",
    ownerId: "40",
    owner: {
      id: "40",
      name: "James Sankale",
      phone: "+254712345673",
      email: "james@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 14,
    },
    status: "approved",
    featured: false,
    views: 110,
    favorites: 9,
    averageRating: 4.6,
    reviewCount: 7,
    createdAt: new Date("2024-02-14"),
    updatedAt: new Date("2024-02-14"),
  },
  {
    id: "42",
    title: "Cultivator - Kisumu",
    description: "Spring-loaded cultivator for weed control and soil aeration. Adjustable working depth.",
    type: "machinery",
    county: "Kisumu",
    size: "11 tine",
    price: 7000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254723456784",
    ownerId: "41",
    owner: {
      id: "41",
      name: "Susan Otieno",
      phone: "+254723456784",
      email: "susan@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: false,
    views: 100,
    favorites: 8,
    averageRating: 4.7,
    reviewCount: 6,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "43",
    title: "Baler Machine - Laikipia",
    description: "Round baler for hay and straw. Produces compact, weather-resistant bales.",
    type: "machinery",
    county: "Laikipia",
    size: "1.2m bale diameter",
    price: 25000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254734567895",
    ownerId: "42",
    owner: {
      id: "42",
      name: "Paul Kariuki",
      phone: "+254734567895",
      email: "paul@example.com",
      verified: true,
      rating: 4.9,
      reviewCount: 16,
    },
    status: "approved",
    featured: true,
    views: 165,
    favorites: 13,
    averageRating: 4.8,
    reviewCount: 11,
    createdAt: new Date("2024-02-16"),
    updatedAt: new Date("2024-02-16"),
  },
  {
    id: "44",
    title: "Greenhouse Equipment - Nyeri",
    description: "Complete greenhouse setup with climate control. Perfect for high-value crops.",
    type: "machinery",
    county: "Nyeri",
    size: "1000 sqm",
    price: 45000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254745678906",
    ownerId: "43",
    owner: {
      id: "43",
      name: "Lucy Wanjiku",
      phone: "+254745678906",
      email: "lucy@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: true,
    views: 155,
    favorites: 12,
    averageRating: 4.7,
    reviewCount: 8,
    createdAt: new Date("2024-02-17"),
    updatedAt: new Date("2024-02-17"),
  },
  {
    id: "45",
    title: "Coffee Pulping Machine - Murang'a",
    description: "Electric coffee pulping machine for post-harvest processing. Maintains bean quality.",
    type: "machinery",
    county: "Murang'a",
    size: "500kg/hour",
    price: 11000,
    priceUnit: "per month",
    photos: ["/john-deere-tractor-kenya.jpg"],
    whatsappNumber: "+254756789017",
    ownerId: "44",
    owner: {
      id: "44",
      name: "Peter Njoroge",
      phone: "+254756789017",
      email: "peter@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 14,
    },
    status: "approved",
    featured: false,
    views: 145,
    favorites: 11,
    averageRating: 4.6,
    reviewCount: 7,
    createdAt: new Date("2024-02-18"),
    updatedAt: new Date("2024-02-18"),
  },

  // Additional diverse listings across more counties
  {
    id: "22",
    title: "Horticultural Land - Kajiado",
    description: "Prime land for greenhouse farming and horticulture. Near Nairobi market access.",
    type: "land",
    cropType: "other",
    county: "Kajiado",
    size: "20 acres",
    price: 90000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254723456782",
    ownerId: "21",
    owner: {
      id: "21",
      name: "Jane Sankale",
      phone: "+254723456782",
      email: "jane@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: false,
    views: 130,
    favorites: 10,
    averageRating: 4.7,
    reviewCount: 8,
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28"),
  },
  {
    id: "23",
    title: "Dairy Farm - Nandi",
    description: "Established dairy farm with modern milking parlor. Includes pasture land and water.",
    type: "land",
    cropType: "other",
    county: "Nandi",
    size: "40 acres",
    price: 160000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254734567893",
    ownerId: "22",
    owner: {
      id: "22",
      name: "Daniel Ruto",
      phone: "+254734567893",
      email: "daniel@example.com",
      verified: true,
      rating: 4.9,
      reviewCount: 16,
    },
    status: "approved",
    featured: true,
    views: 170,
    favorites: 13,
    averageRating: 4.8,
    reviewCount: 11,
    createdAt: new Date("2024-01-06"),
    updatedAt: new Date("2024-01-06"),
  },
  {
    id: "24",
    title: "Avocado Orchard - Murang'a",
    description: "Mature avocado trees ready for harvesting. Export quality Hass variety.",
    type: "plantation",
    cropType: "other",
    county: "Murang'a",
    size: "15 acres",
    price: 130000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254745678904",
    ownerId: "23",
    owner: {
      id: "23",
      name: "Lucy Wanjiru",
      phone: "+254745678904",
      email: "lucy@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 14,
    },
    status: "approved",
    featured: false,
    views: 160,
    favorites: 12,
    averageRating: 4.6,
    reviewCount: 7,
    createdAt: new Date("2024-01-29"),
    updatedAt: new Date("2024-01-29"),
  },
  {
    id: "25",
    title: "Mango Plantation - Kilifi",
    description: "Coastal mango plantation with various varieties. Excellent for export market.",
    type: "plantation",
    cropType: "other",
    county: "Kilifi",
    size: "35 acres",
    price: 95000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254756789015",
    ownerId: "24",
    owner: {
      id: "24",
      name: "Hassan Mohamed",
      phone: "+254756789015",
      email: "hassan@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: false,
    views: 150,
    favorites: 11,
    averageRating: 4.7,
    reviewCount: 8,
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-01-30"),
  },
  {
    id: "26",
    title: "Wheat Farm - Narok",
    description: "Large scale wheat farming land with storage facilities. Mechanization ready.",
    type: "land",
    cropType: "other",
    county: "Narok",
    size: "300 acres",
    price: 200000,
    priceUnit: "per season",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254767890126",
    ownerId: "25",
    owner: {
      id: "25",
      name: "William Sankale",
      phone: "+254767890126",
      email: "william@example.com",
      verified: true,
      rating: 4.9,
      reviewCount: 16,
    },
    status: "approved",
    featured: true,
    views: 180,
    favorites: 14,
    averageRating: 4.8,
    reviewCount: 11,
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "27",
    title: "Poultry Farm - Kirinyaga",
    description: "Modern poultry farming facility with automated systems. Includes feed storage.",
    type: "land",
    cropType: "other",
    county: "Kirinyaga",
    size: "5 acres",
    price: 75000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254778901237",
    ownerId: "26",
    owner: {
      id: "26",
      name: "Agnes Wanjiku",
      phone: "+254778901237",
      email: "agnes@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: false,
    views: 165,
    favorites: 12,
    averageRating: 4.7,
    reviewCount: 8,
    createdAt: new Date("2024-01-31"),
    updatedAt: new Date("2024-01-31"),
  },
  {
    id: "28",
    title: "Fish Farm - Kisii",
    description: "Established fish farming ponds with fingerling supply. Ready for tilapia production.",
    type: "land",
    cropType: "other",
    county: "Kisii",
    size: "8 acres",
    price: 50000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254789012348",
    ownerId: "27",
    owner: {
      id: "27",
      name: "George Nyamweya",
      phone: "+254789012348",
      email: "george@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 14,
    },
    status: "approved",
    featured: false,
    views: 155,
    favorites: 11,
    averageRating: 4.6,
    reviewCount: 7,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "29",
    title: "Sunflower Farm - Baringo",
    description: "Arid land suitable for sunflower cultivation. Drought resistant and profitable.",
    type: "land",
    cropType: "other",
    county: "Baringo",
    size: "120 acres",
    price: 65000,
    priceUnit: "per season",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254790123459",
    ownerId: "28",
    owner: {
      id: "28",
      name: "John Cheruiyot",
      phone: "+254790123459",
      email: "john@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 15,
    },
    status: "approved",
    featured: false,
    views: 145,
    favorites: 10,
    averageRating: 4.7,
    reviewCount: 8,
    createdAt: new Date("2024-02-02"),
    updatedAt: new Date("2024-02-02"),
  },
  {
    id: "30",
    title: "Coconut Plantation - Kwale",
    description: "Coastal coconut plantation with mature trees. Perfect for copra and coconut oil production.",
    type: "plantation",
    cropType: "other",
    county: "Kwale",
    size: "45 acres",
    price: 85000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254701234570",
    ownerId: "29",
    owner: {
      id: "29",
      name: "Fatuma Ali",
      phone: "+254701234570",
      email: "fatuma@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 14,
    },
    status: "approved",
    featured: false,
    views: 135,
    favorites: 11,
    averageRating: 4.6,
    reviewCount: 7,
    createdAt: new Date("2024-02-03"),
    updatedAt: new Date("2024-02-03"),
  },

  // Warehouses and Storage
  {
    id: "46",
    title: "Agricultural Storage Warehouse - Nairobi",
    description:
      "Modern 5000 sqm storage warehouse with loading bay and security. Perfect for grain and agricultural product storage. Climate-controlled sections available.",
    type: "warehouse",
    county: "Nairobi",
    size: "5000 sqm",
    price: 250000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254712345674",
    ownerId: "45",
    owner: {
      id: "45",
      name: "Nairobi Logistics Ltd",
      phone: "+254712345674",
      email: "logistics@example.com",
      verified: true,
      rating: 4.9,
      reviewCount: 18,
    },
    status: "approved",
    featured: true,
    views: 320,
    favorites: 28,
    averageRating: 4.8,
    reviewCount: 14,
    createdAt: new Date("2024-02-19"),
    updatedAt: new Date("2024-02-19"),
  },
  {
    id: "47",
    title: "Cold Storage Facility - Nakuru",
    description:
      "Temperature-controlled warehouse for perishable goods. Maintains 2-8°C temperature. Ideal for dairy, vegetables, and fruits.",
    type: "warehouse",
    county: "Nakuru",
    size: "3000 sqm",
    price: 180000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254723456785",
    ownerId: "46",
    owner: {
      id: "46",
      name: "Cold Chain Solutions",
      phone: "+254723456785",
      email: "coldchain@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 17,
    },
    status: "approved",
    featured: true,
    views: 285,
    favorites: 25,
    averageRating: 4.7,
    reviewCount: 12,
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "48",
    title: "Grain Silo Complex - Eldoret",
    description:
      "Complete grain storage facility with 8 silos. Total capacity 2000 tons. Includes drying and cleaning equipment.",
    type: "warehouse",
    county: "Uasin Gishu",
    size: "2000 ton capacity",
    price: 350000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254734567896",
    ownerId: "47",
    owner: {
      id: "47",
      name: "Uasin Gishu Grain Hub",
      phone: "+254734567896",
      email: "grainhub@example.com",
      verified: true,
      rating: 4.9,
      reviewCount: 19,
    },
    status: "approved",
    featured: true,
    views: 315,
    favorites: 27,
    averageRating: 4.8,
    reviewCount: 15,
    createdAt: new Date("2024-02-21"),
    updatedAt: new Date("2024-02-21"),
  },
  {
    id: "49",
    title: "Commercial Storage Unit - Kisumu",
    description:
      "Individual storage units ranging from 100-500 sqm. Secure facility with 24/7 security. Perfect for traders and farmers.",
    type: "warehouse",
    county: "Kisumu",
    size: "2000 sqm total",
    price: 120000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254745678907",
    ownerId: "48",
    owner: {
      id: "48",
      name: "Kisumu Storage Solutions",
      phone: "+254745678907",
      email: "storage@example.com",
      verified: true,
      rating: 4.7,
      reviewCount: 16,
    },
    status: "approved",
    featured: false,
    views: 195,
    favorites: 16,
    averageRating: 4.6,
    reviewCount: 10,
    createdAt: new Date("2024-02-22"),
    updatedAt: new Date("2024-02-22"),
  },
  {
    id: "50",
    title: "Fumigation Ready Warehouse - Mombasa",
    description:
      "Export-ready warehouse with fumigation chamber. Meets international standards for agricultural product export. Port proximity.",
    type: "warehouse",
    county: "Mombasa",
    size: "4000 sqm",
    price: 280000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254756789018",
    ownerId: "49",
    owner: {
      id: "49",
      name: "Mombasa Port Logistics",
      phone: "+254756789018",
      email: "portlogistics@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 17,
    },
    status: "approved",
    featured: false,
    views: 220,
    favorites: 18,
    averageRating: 4.7,
    reviewCount: 11,
    createdAt: new Date("2024-02-23"),
    updatedAt: new Date("2024-02-23"),
  },
  {
    id: "51",
    title: "Agro-Processing Facility - Murang'a",
    description:
      "Industrial facility with processing equipment. Includes offices, quality control lab, and worker facilities. Ready for immediate use.",
    type: "warehouse",
    county: "Murang'a",
    size: "6000 sqm",
    price: 320000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254767890128",
    ownerId: "50",
    owner: {
      id: "50",
      name: "Murang'a Processing Co",
      phone: "+254767890128",
      email: "processing@example.com",
      verified: true,
      rating: 4.9,
      reviewCount: 18,
    },
    status: "approved",
    featured: false,
    views: 240,
    favorites: 20,
    averageRating: 4.8,
    reviewCount: 13,
    createdAt: new Date("2024-02-24"),
    updatedAt: new Date("2024-02-24"),
  },
  {
    id: "52",
    title: "Distribution Hub - Nairobi West",
    description:
      "Strategic location for agricultural product distribution. 24/7 operations. Multiple loading docks and modern inventory system.",
    type: "warehouse",
    county: "Nairobi",
    size: "3500 sqm",
    price: 200000,
    priceUnit: "per year",
    photos: ["/agricultural-land-kenya-maize.jpg"],
    whatsappNumber: "+254778901239",
    ownerId: "51",
    owner: {
      id: "51",
      name: "Nairobi Distribution Network",
      phone: "+254778901239",
      email: "distribution@example.com",
      verified: true,
      rating: 4.8,
      reviewCount: 16,
    },
    status: "approved",
    featured: false,
    views: 210,
    favorites: 17,
    averageRating: 4.7,
    reviewCount: 12,
    createdAt: new Date("2024-02-25"),
    updatedAt: new Date("2024-02-25"),
  },
]

// Counties in Kenya
export const kenyanCounties = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
]

export const cropTypes: { value: CropType; label: string }[] = [
  { value: "coffee", label: "Coffee" },
  { value: "tea", label: "Tea" },
  { value: "maize", label: "Maize" },
  { value: "sugarcane", label: "Sugarcane" },
  { value: "cotton", label: "Cotton" },
  { value: "other", label: "Other" },
]

export const listingTypes: { value: ListingType; label: string }[] = [
  { value: "land", label: "Agricultural Land" },
  { value: "plantation", label: "Plantation" },
  { value: "machinery", label: "Farm Machinery" },
  { value: "warehouse", label: "Warehouses & Storage" },
]

export const mockBlogPosts = [
  {
    id: "1",
    title: "Best Practices for Sustainable Coffee Farming in Kenya",
    excerpt:
      "Learn how to maximize your coffee yield while maintaining environmental sustainability. Our expert tips cover soil management, water conservation, and pest control.",
    content: "Full article content about sustainable coffee farming practices...",
    category: "tips",
    author: "Dr. Peter Kamau",
    image: "/sustainable-coffee-farming.jpg",
    readTime: 5,
    featured: true,
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-01-08"),
  },
  {
    id: "2",
    title: "Q1 2025 Agricultural Market Update - Kenya",
    excerpt:
      "Comprehensive analysis of crop prices, market trends, and opportunities for Kenyan farmers in the first quarter of 2025.",
    content: "Full market analysis content...",
    category: "market_update",
    author: "Market Analysis Team",
    image: "/market-update-agriculture.jpg",
    readTime: 7,
    featured: true,
    createdAt: new Date("2025-01-06"),
    updatedAt: new Date("2025-01-06"),
  },
  {
    id: "3",
    title: "Modern Machinery Reduces Tea Harvesting Time by 40%",
    excerpt:
      "Discover the latest agricultural machinery innovations that are revolutionizing tea harvesting in Kenya and improving farmer profitability.",
    content: "Full article about modern tea harvesting machinery...",
    category: "technology",
    author: "Innovation Weekly",
    image: "/tea-harvesting-machinery.jpg",
    readTime: 6,
    featured: true,
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-01-05"),
  },
  {
    id: "4",
    title: "Regenerative Agriculture: Building Healthier Soils",
    excerpt:
      "Explore regenerative farming techniques that improve soil health, increase crop productivity, and sequester carbon while reducing input costs.",
    content: "Full content about regenerative agriculture...",
    category: "sustainability",
    author: "Dr. Susan Kiplagat",
    image: "/regenerative-agriculture-soil.jpg",
    readTime: 8,
    featured: false,
    createdAt: new Date("2025-01-04"),
    updatedAt: new Date("2025-01-04"),
  },
  {
    id: "5",
    title: "Maize Production Reaches Record High in 2024",
    excerpt:
      "Government reports show a 25% increase in maize production this year. Learn what farmers are doing differently and how you can boost your yields.",
    content: "Full news article about maize production records...",
    category: "news",
    author: "Agricultural Ministry",
    image: "/maize-production-harvest.jpg",
    readTime: 4,
    featured: false,
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-02"),
  },
  {
    id: "6",
    title: "Precision Farming with IoT Sensors - The Future",
    excerpt:
      "Smart sensors and data analytics are transforming how farmers manage their crops. Learn how to implement precision farming on your land.",
    content: "Full technical guide to precision farming...",
    category: "technology",
    author: "Tech Innovation Hub",
    image: "/iot-sensors-farming.jpg",
    readTime: 9,
    featured: false,
    createdAt: new Date("2024-12-30"),
    updatedAt: new Date("2024-12-30"),
  },
]

export const mockUsers: User[] = [
  {
    id: "1",
    email: "farmer@example.com",
    name: "John Farmer",
    role: "farmer",
    phone: "+254712345678",
    county: "Nakuru",
    verified: true,
    rating: 4.5,
    reviewCount: 12,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    email: "owner@example.com",
    name: "Property Owner",
    role: "owner",
    phone: "+254723456789",
    county: "Kiambu",
    verified: true,
    rating: 4.8,
    reviewCount: 18,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "admin1",
    email: "admin@farmlease.com",
    name: "Admin Officer",
    role: "admin",
    phone: "+254734567890",
    verified: true,
    createdAt: new Date("2024-01-01"),
  },
]
